name: dentaltid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^4.0.7
  cloud_firestore: ^6.1.0
  csv: ^6.0.0
  file_picker: ^10.3.3
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  fl_chart: ^1.1.1
  flutter_riverpod: ^2.5.1
  go_router: ^16.3.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_sqlcipher: ^3.4.0

  shared_preferences: ^2.5.3
  aes_crypt_null_safe: ^3.1.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen: ^5.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  generate: true
