name: dentaltid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.3.2
  cloud_firestore: ^6.1.0
  csv: ^6.0.0
  file_picker: ^8.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  fl_chart: ^1.1.1
  flutter_riverpod: ^2.5.1
  go_router: ^16.3.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_sqlcipher: ^3.4.0
  crypto: ^3.0.6

  shared_preferences: ^2.5.3
  aes_crypt_null_safe: ^3.1.1
  sqflite_common_ffi: ^2.3.6
  flutter_secure_storage: ^9.2.2
  firebase_auth: ^6.1.2
  uuid: ^4.5.2
  logging: ^1.2.0
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  google_fonts: ^6.3.3
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  shelf_router: ^1.1.4
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  flutter_twain_scanner: ^2.0.1
  image: ^4.3.0
  qr_flutter: ^4.1.0
  printing: ^5.14.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen: ^5.0.0
  build_runner: ^2.1.11
  mockito: ^5.6.1
  flutter_distributor: ^0.0.2
  flutter_launcher_icons: ^0.13.1
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/DT!d.png"
  windows:
    generate: true
    image_path: "assets/images/DT!d.png"
    icon_size: 256 # Increased from 48 for high-res display

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_distributor:
  releases:
    - name: windows-x64
      jobs:
        - name: release
          package:
            platform: windows
            target: exe
          artifacts:
            - path: build/windows/x64/runner/Release/dentaltid.exe
          args:
            installer: inno
    - name: windows-x86
      jobs:
        - name: release
          package:
            platform: windows
            target: exe
          artifacts:
            - path: build/windows/x86/runner/Release/dentaltid.exe
          args:
            installer: inno
